#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<EOF
Usage:
  ARIADNE_REPO_PATH=/path/to/repo \\
  ARIADNE_PROJECT_BACKGROUND_PATH=/path/to/PROJECT_BACKGROUND.md \\
  $0

  $0 repo_path [output_path]
  $0 repo_path project_name output_path
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if (( $# > 3 )); then
  usage
  exit 1
fi

REPO_PATH="${ARIADNE_REPO_PATH:-${1:-}}"
OUTPUT_PATH="${ARIADNE_PROJECT_BACKGROUND_PATH:-}"

if [[ -z "${OUTPUT_PATH}" ]]; then
  if (( $# == 3 )); then
    OUTPUT_PATH="$3"
  else
    OUTPUT_PATH="${2:-}"
  fi
fi

if [[ -z "${REPO_PATH}" ]]; then
  usage
  exit 1
fi

if [[ ! -d "${REPO_PATH}" ]]; then
  echo "Repo path does not exist or is not a directory: ${REPO_PATH}" >&2
  exit 1
fi

if [[ -z "${OUTPUT_PATH}" ]]; then
  REPO_ABS="$(cd "${REPO_PATH}" && pwd)"
  REPO_NAME="$(basename "${REPO_ABS}")"

  # Compute 8-char hash of the absolute repo path (portable: sha256sum on Linux, shasum on macOS).
  if command -v sha256sum &>/dev/null; then
    HASH="$(printf '%s' "${REPO_ABS}" | sha256sum | cut -c1-8)"
  elif command -v shasum &>/dev/null; then
    HASH="$(printf '%s' "${REPO_ABS}" | shasum -a 256 | cut -c1-8)"
  else
    HASH="$(printf '%s' "${REPO_ABS}" | cksum | awk '{printf "%08x", $1}')"
  fi

  ARIADNE_HOME_DIR="${ARIADNE_HOME:-${HOME}/.ariadne}"
  OUTPUT_PATH="${ARIADNE_HOME_DIR}/project-backgrounds/${REPO_NAME}-${HASH}/PROJECT_BACKGROUND.md"
fi

echo "Refreshing PROJECT_BACKGROUND.md ..."

TMP_OUTPUT="$(mktemp)"
trap 'rm -f "${TMP_OUTPUT}"' EXIT

codex exec \
  --cd "${REPO_PATH}" \
  --sandbox read-only \
  --skip-git-repo-check \
  --ephemeral \
  --color never \
  --output-last-message "${TMP_OUTPUT}" \
  - <<'PROMPT'
You are refreshing Ariadne's PROJECT_BACKGROUND.md for this repository.

Inspect the repo read-only. Do not edit files. Do not read or expose secrets. Avoid .env files, private keys, credentials, tokens, and any file that appears secret-bearing.

Create a concise ~200 line Markdown project background for Ariadne's voice conversation agent. This document is orientation, not an implementation brief. It should help Ariadne answer basic questions about the repo and decide when fresh repo investigation is needed.

Return only the raw Markdown document. Do not wrap it in code fences or add explanatory text before or after it.

Write the document with this structure:

# Project Background

## What This Project / Repo Does

## Current Architectural Overview

## Components And Pieces

## Last Refreshed

For "Last Refreshed", include the current date/time if available from the environment or shell context; otherwise write "Generated by Codex repo refresh".

Keep the document factual and grounded. Include file paths where useful, but avoid long code excerpts.
PROMPT

mkdir -p "$(dirname "${OUTPUT_PATH}")"
mv "${TMP_OUTPUT}" "${OUTPUT_PATH}"
trap - EXIT

echo "Updated PROJECT_BACKGROUND.md: ${OUTPUT_PATH}"
