import os
import re
from datetime import datetime
from pathlib import Path

import openai
from loguru import logger

from ariadne.paths import get_briefs_dir
from ariadne.session import AriadneSession


def _is_ariadne_dir_gitignored(repo_path: str) -> bool:
    gitignore = Path(repo_path) / ".gitignore"
    if not gitignore.exists():
        return False
    lines = gitignore.read_text(encoding="utf-8").splitlines()
    return any(line.strip() in (".ariadne", ".ariadne/") for line in lines)


def _slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    text = re.sub(r"-+", "-", text)
    text = text.strip("-")
    return text[:60] or "implementation-brief"


_BRIEF_PROMPT_TEMPLATE = """\
You are a senior engineer generating a structured implementation brief.

## Task Context

{problem_context}

## Project Background

{project_background}

---

Generated by: Ariadne
Generated at: {generated_at}
Source: voice investigation

Generate a Markdown implementation brief using this exact structure:

# Implementation Brief: <title>

Generated by: Ariadne
Generated at: {generated_at}
Source: voice investigation

## Context

## Goal

## Current Findings

## Proposed Approach

## Likely Files To Touch

## Risks / Unknowns

## Test Plan

## Acceptance Criteria

## Prompt For Coding Agent

Rules:
- Do not include secrets or environment variable values.
- Do not claim that code was changed.
- Be concrete and grounded in the findings.
- "Prompt For Coding Agent" must be a concise, self-contained prompt that can be pasted into Codex or Claude Code.
- Respond with ONLY the Markdown document, no preamble.
"""


class ImplementationDocWriter:
    async def write_doc(self, problem_context: str, session: AriadneSession) -> dict | None:
        """
        Generate an implementation brief from problem_context and save it to the repo.
        Returns {"summary_for_voice": str, "full_result": str} or None on failure.
        """
        repo_path = os.getenv("ARIADNE_REPO_PATH", "").strip()
        if not repo_path:
            logger.error("ImplementationDocWriter: ARIADNE_REPO_PATH is not set")
            return None

        session.logger.log(
            "runtime",
            "runtime.implementation_doc_started",
            {"turn_id": session.current_turn_id},
            turn_id=session.current_turn_id,
        )

        try:
            content, title = await self._generate_brief(problem_context)
        except Exception as exc:
            logger.exception(f"ImplementationDocWriter: OpenAI call failed: {exc}")
            session.logger.log(
                "runtime",
                "runtime.implementation_doc_error",
                {"error": str(exc)},
                turn_id=session.current_turn_id,
            )
            return None

        slug = _slugify(title)
        timestamp = datetime.now().strftime("%m%d-%H%M")
        filename = f"ariadne-{slug}-{timestamp}.md"

        output_dir = get_briefs_dir(repo_path)
        output_path = output_dir / filename

        if not _is_ariadne_dir_gitignored(repo_path):
            logger.warning(
                f"'{repo_path}/.ariadne/' is not listed in .gitignore. "
                "Add '.ariadne/' to avoid accidentally committing session artifacts."
            )

        # Path safety check.
        try:
            output_path.resolve().relative_to(output_dir.resolve())
        except ValueError:
            logger.error(f"ImplementationDocWriter: path escape detected: {output_path}")
            return None

        if not filename.startswith("ariadne-") or not filename.endswith(".md"):
            logger.error(f"ImplementationDocWriter: filename safety check failed: {filename}")
            return None

        try:
            output_dir.mkdir(parents=True, exist_ok=True)
            output_path.write_text(content, encoding="utf-8")
        except Exception as exc:
            logger.exception(f"ImplementationDocWriter: file write failed: {exc}")
            session.logger.log(
                "runtime",
                "runtime.implementation_doc_error",
                {"error": str(exc), "path": str(output_path)},
                turn_id=session.current_turn_id,
            )
            return None

        session.logger.log(
            "runtime",
            "runtime.implementation_doc_written",
            {"path": str(output_path)},
            turn_id=session.current_turn_id,
        )
        session.logger._append(f"\nImplementation brief written:\n{output_path}\n")
        logger.info(f"ImplementationDocWriter: brief saved to {output_path}")

        rel_path = str(output_path).replace(str(Path(repo_path).resolve()), "").lstrip("/")
        return {
            "summary_for_voice": f"Done. I saved the implementation brief to {rel_path}.",
            "full_result": content,
        }

    async def _generate_brief(self, problem_context: str) -> tuple[str, str]:
        project_bg = ""
        project_bg_path = os.getenv("ARIADNE_PROJECT_BACKGROUND_PATH", "")
        if project_bg_path:
            try:
                project_bg = Path(project_bg_path).read_text(encoding="utf-8").strip()
            except Exception:
                pass

        prompt = _BRIEF_PROMPT_TEMPLATE.format(
            problem_context=problem_context,
            project_background=project_bg or "(not available)",
            generated_at=datetime.utcnow().isoformat() + "Z",
        )

        client = openai.AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        response = await client.chat.completions.create(
            model=os.getenv("OPENAI_MODEL", "gpt-4.1"),
            messages=[{"role": "user", "content": prompt}],
            max_tokens=2000,
        )
        content = (response.choices[0].message.content or "").strip()

        title = "implementation-brief"
        for line in content.splitlines():
            if line.startswith("# Implementation Brief:"):
                title = line.replace("# Implementation Brief:", "").strip()
                break

        return content, title
